// lib/services/kifu_export_service.dart
// 棋譜をKIF形式テキストに変換するサービス

import '../piece.dart';

class KifuExportService {
  static const _rankKanji = [
    '一', '二', '三', '四', '五', '六', '七', '八', '九'
  ];

  /// KifuMove リストを標準KIF形式テキストに変換する。
  /// 座標はすべて先手視点（内部board座標から直接変換）。
  static String toKifString(
    List<KifuMove> moves, {
    String p1Name = '先手',
    String p2Name = '後手',
    String? dateOverride,
  }) {
    final now = DateTime.now();
    final date = dateOverride ??
        '${now.year}/${now.month.toString().padLeft(2, '0')}/${now.day.toString().padLeft(2, '0')} '
        '${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}:${now.second.toString().padLeft(2, '0')}';

    final buf = StringBuffer();
    buf.writeln('# KIF形式棋譜ファイル');
    buf.writeln('# Generated by 効棋');
    buf.writeln('開始日時：$date');
    buf.writeln('手合割：平手');
    buf.writeln('先手：$p1Name');
    buf.writeln('後手：$p2Name');
    buf.writeln('手数----指手---------消費時間--');

    for (final move in moves) {
      buf.writeln(_toKifLine(move));
    }

    if (moves.isNotEmpty) {
      // 最終手の指し手側が負け（詰まれた側は相手）
      final lastMover = moves.last.p1 ? '先手' : '後手';
      final winner = moves.last.p1 ? '後手' : '先手';
      buf.writeln('${moves.length + 1} 投了');
      buf.writeln('まで${moves.length}手で$lastMoverの負け（$winner勝ち）');
    }

    return buf.toString();
  }

  static String _toKifLine(KifuMove m) {
    final num = m.num.toString().padLeft(4);
    final notation = _toKifNotation(m);
    final time = _formatTime(m.elapsedSec);
    return '$num $notation   $time';
  }

  static String _toKifNotation(KifuMove m) {
    // KIF座標: file = 9 - col_index, rank = row_index + 1（常に先手視点の絶対座標）
    final toFile = 9 - m.tc;
    final toRankIdx = m.tr; // 0-indexed → _rankKanji[toRankIdx]

    if (m.drop != null) {
      // 打ち駒: "{file}{rank_kanji}{piece}打"
      return '$toFile${_rankKanji[toRankIdx]}${pieceLabel(m.drop!)}打';
    }

    // 盤上移動: "{toFile}{toRank}{piece}{promote?}({fromFile}{fromRank})"
    final fromFile = 9 - m.fc;
    final fromRank = m.fr + 1;
    final pieceName = _extractPieceLabel(m.note);
    final promote = m.promote ? '成' : '';

    return '$toFile${_rankKanji[toRankIdx]}$pieceName$promote($fromFile$fromRank)';
  }

  // noteから駒ラベルを抽出する。
  // note形式: "{file_digit}{rank_kanji}{piece_label}{optional:成}"
  // 先頭2文字（数字+漢字）を除いた残りが駒名（"成"サフィックスは除去）。
  static String _extractPieceLabel(String note) {
    if (note.length < 3) return '';
    var piece = note.substring(2);
    if (piece.endsWith('成')) piece = piece.substring(0, piece.length - 1);
    return piece;
  }

  static String _formatTime(int sec) {
    if (sec <= 0) return '00:00';
    final m = (sec ~/ 60).toString().padLeft(2, '0');
    final s = (sec % 60).toString().padLeft(2, '0');
    return '$m:$s';
  }
}
