import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { doc, setDoc, updateDoc, getDoc } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId:'t', firestore:{ rules: readFileSync(process.argv[2],'utf8'), host:'127.0.0.1', port:8080 }});
const a = env.authenticatedContext('A').firestore(), b = env.authenticatedContext('B').firestore(), c = env.authenticatedContext('C').firestore();
const q=(id,u)=>({user_id:u,status:'waiting',rating:700});
let ok=0, ng=0; const t=async(n,p)=>{try{await p;ok++;console.log('PASS',n)}catch(e){ng++;console.log('FAIL',n,e.message.slice(0,80))}};
await t('A joins queue', assertSucceeds(setDoc(doc(a,'matching_queue/qa'),q('qa','A'))));
await t('B joins queue', assertSucceeds(setDoc(doc(b,'matching_queue/qb'),q('qb','B'))));
await t('A cannot enqueue as B', assertFails(setDoc(doc(a,'matching_queue/qx'),q('qx','B'))));
await t('A cannot enqueue as matched', assertFails(setDoc(doc(a,'matching_queue/qy'),{user_id:'A',status:'matched'})));
await t('A creates match with B', assertSucceeds(setDoc(doc(a,'matches/m1'),{player1_id:'A',player2_id:'B',status:'playing'})));
await t('C cannot create match for A,B', assertFails(setDoc(doc(c,'matches/m2'),{player1_id:'A',player2_id:'B'})));
await t('A marks B queue matched', assertSucceeds(updateDoc(doc(a,'matching_queue/qb'),{status:'matched',matched_with:'A',match_id:'m1'})));
await t('B cannot re-match already matched', assertFails(updateDoc(doc(c,'matching_queue/qb'),{status:'matched',match_id:'z'})));
await t('C cannot change A rating', assertFails(updateDoc(doc(c,'matching_queue/qa'),{rating:3000})));
await t('C cannot cancel A queue', assertFails(updateDoc(doc(c,'matching_queue/qa'),{status:'cancelled'})));
await t('A can cancel own', assertSucceeds(updateDoc(doc(a,'matching_queue/qa'),{status:'cancelled'})));
await t('player B updates match', assertSucceeds(updateDoc(doc(b,'matches/m1'),{status:'finished'})));
await t('C cannot update match', assertFails(updateDoc(doc(c,'matches/m1'),{status:'cancelled'})));
await t('anyone auth can read match', assertSucceeds(getDoc(doc(c,'matches/m1'))));
console.log(`${ok} pass, ${ng} fail`); await env.cleanup(); process.exit(ng?1:0);
