// lib/kif_utils_stub.dart — KIF形式 エンコード / デコード（native/stub用）
// dart:html を使わないため全プラットフォームで動作する

import 'piece.dart';

const _fwFiles = '１２３４５６７８９';   // full-width file digits
const _kanjiRanks = '一二三四五六七八九'; // kanji rank characters

// piece char → PieceType (for KIF import)
const _charToPt = <String, PieceType>{
  '歩': PieceType.pawn,   '香': PieceType.lance,  '桂': PieceType.knight,
  '銀': PieceType.silver, '金': PieceType.gold,   '角': PieceType.bishop,
  '飛': PieceType.rook,   '王': PieceType.king,   '玉': PieceType.king,
  'と': PieceType.promotedPawn,   '全': PieceType.promotedSilver,
  '圭': PieceType.promotedKnight, '杏': PieceType.promotedLance,
  '馬': PieceType.promotedBishop, '龍': PieceType.promotedRook,
  '竜': PieceType.promotedRook,
};

// ── KIF エンコード ──────────────────────────────────

class KifEncoder {
  static String encode(
    List<KifuMove> moves, {
    String? date,
    String? result,
    String? handicap,
  }) {
    final sb = StringBuffer()
      ..writeln('# KIF形式棋譜ファイル')
      ..writeln('# Generated by 効棋 - Kouki')
      ..writeln('開始日時：${date ?? _today()}')
      ..writeln('手合割：${handicap ?? '平手'}')
      ..writeln('先手：先手')
      ..writeln('後手：後手')
      ..writeln('手数----指手---------消費時間--');
    for (final km in moves) sb.writeln(_line(km));
    if (result != null && result.isNotEmpty) {
      sb.writeln('まで${moves.length}手で$result');
    }
    return sb.toString();
  }

  static String _line(KifuMove km) {
    final toFile = 9 - km.tc;
    final toRank = km.tr + 1;
    final toSq = '${_fwFiles[toFile - 1]}${_kanjiRanks[toRank - 1]}';
    final num = km.num.toString().padLeft(4);

    if (km.drop != null) {
      return '$num $toSq${pieceLabel(km.drop!)}打   (00:00/00:00:00)';
    }
    // piece char from note[2] (destination is first 2 chars of note)
    final pc = km.note.length > 2 ? km.note[2] : '?';
    final prom = km.promote ? '成' : '';
    final fromFile = 9 - km.fc;
    final fromRank = km.fr + 1;
    return '$num $toSq$pc$prom($fromFile$fromRank)   (00:00/00:00:00)';
  }

  static String _today() => DateTime.now().toString().substring(0, 10);

  /// '手合割：' 行を解析して手合割文字列を返す（見つからなければ null）。
  static String? extractHandicap(String kif) {
    for (final line in kif.split(RegExp(r'\r?\n'))) {
      if (line.startsWith('手合割：')) {
        return line.substring('手合割：'.length).trim();
      }
    }
    return null;
  }
}

// ── KIF デコード ──────────────────────────────────

class KifDecoder {
  /// KIF文字列 → moves。失敗時は null。
  static List<KifuMove>? decode(String kif) {
    try {
      final moves = <KifuMove>[];
      for (final raw in kif.split(RegExp(r'\r?\n'))) {
        final m = _parseLine(raw.trim());
        if (m != null) moves.add(m);
      }
      return moves.isEmpty ? null : moves;
    } catch (_) {
      return null;
    }
  }

  static KifuMove? _parseLine(String line) {
    final nm = RegExp(r'^\s*(\d+)\s+(.+)$').firstMatch(line);
    if (nm == null) return null;
    final num = int.tryParse(nm.group(1)!);
    if (num == null || num < 1) return null;
    // strip time "(x:xx/...)"
    var mv = nm.group(2)!.replaceAll(RegExp(r'\(\d+:\d+/[^)]*\)\s*$'), '').trim();

    // special moves: resign, etc.
    if (mv.contains('投了') || mv.contains('中断') ||
        mv.contains('千日手') || mv.contains('持将棋')) return null;

    // first char must be full-width file digit
    if (mv.isEmpty || !_fwFiles.contains(mv[0])) return null;
    final toFile = _fwFiles.indexOf(mv[0]) + 1;
    if (mv.length < 2 || !_kanjiRanks.contains(mv[1])) return null;
    final toRank = _kanjiRanks.indexOf(mv[1]) + 1;
    final tr = toRank - 1;
    final tc = 9 - toFile;
    final rest = mv.substring(2); // piece + action + (from)

    final bool p1 = num % 2 == 1;

    // drop: piece + 打
    if (rest.contains('打')) {
      final pc = _charToPt[rest[0]];
      if (pc == null) return null;
      final note = '${9 - tc}${_kanjiRanks[tr]}${pieceLabel(pc)}打';
      return KifuMove(num, p1, note,
          fr: -1, fc: -1, tr: tr, tc: tc, drop: pc);
    }

    // normal/promote: piece[成](fromFile fromRank)
    if (rest.isEmpty || !_charToPt.containsKey(rest[0])) return null;
    final promote = rest.length > 1 && rest[1] == '成';
    final fromM = RegExp(r'\((\d)(\d)\)').firstMatch(rest);
    if (fromM == null) return null;
    final fromFile = int.parse(fromM.group(1)!);
    final fromRank = int.parse(fromM.group(2)!);
    final fr = fromRank - 1;
    final fc = 9 - fromFile;
    final note = '${9 - tc}${_kanjiRanks[tr]}${rest[0]}${promote ? '成' : ''}';
    return KifuMove(num, p1, note,
        fr: fr, fc: fc, tr: tr, tc: tc, promote: promote);
  }
}

// ── ファイル操作（no-op stubs for non-web platforms） ──────────────────────

/// No-op on non-web platforms
void downloadKifFile(String content, String filename) {}

/// No-op on non-web platforms (callback is never called)
void pickKifFile(void Function(String content, String filename) onLoaded) {}
